import type { Metadata } from 'next';
import { pretendard } from '@/app/fonts';
import './globals.css';

import { Providers } from './Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className={`font-pretendard antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
